<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <AssemblyName>RavenM</AssemblyName>
    <Description>A Ravenfield multiplayer mod.</Description>
    <Version>0.7</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <BaseIntermediateOutputPath>obj\</BaseIntermediateOutputPath>
    <DefaultRavenfieldManagedDir>C:\Program Files (x86)\Steam\steamapps\common\Ravenfield\ravenfield_Data\Managed</DefaultRavenfieldManagedDir>
    <RavenfieldManagedDir Condition="'$(RavenfieldManagedDir)' == '' and Exists('$(DefaultRavenfieldManagedDir)\Assembly-CSharp.dll')">$(DefaultRavenfieldManagedDir)</RavenfieldManagedDir>
    <RavenfieldManagedDir Condition="'$(RavenfieldManagedDir)' == ''">libs</RavenfieldManagedDir>
  </PropertyGroup>

   <ItemGroup>
    <None Remove="assets\marker.png" />
    <None Remove="assets\marker_left.png" />
    <None Remove="assets\marker_right.png" />
    <None Remove="assets\mic.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="assets\marker.png" />
    <EmbeddedResource Include="assets\marker_left.png" />
    <EmbeddedResource Include="assets\marker_right.png" />
	  <EmbeddedResource Include="assets\mic.png" />
    <EmbeddedResource Include="assets\kickanimcontroller" />
  <EmbeddedResource Include="assets\UIBundle" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.0.8" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.4.21" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="1.1.0" />
    <PackageReference Include="UnityEngine.Modules" Version="5.6.0" IncludeAssets="compile" />
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>
  
 <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(RavenfieldManagedDir)\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>$(RavenfieldManagedDir)\Assembly-CSharp-firstpass.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>$(RavenfieldManagedDir)\com.rlabrecque.steamworks.net.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="netstandard">
      <HintPath>$(RavenfieldManagedDir)\netstandard.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(RavenfieldManagedDir)\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(RavenfieldManagedDir)\UnityEngine.AudioModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(RavenfieldManagedDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(RavenfieldManagedDir)\UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(RavenfieldManagedDir)\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(RavenfieldManagedDir)\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(RavenfieldManagedDir)\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(RavenfieldManagedDir)\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(RavenfieldManagedDir)\UnityEngine.UIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>$(RavenfieldManagedDir)\UnityEngine.AnimationModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>$(RavenfieldManagedDir)\UnityEngine.AssetBundleModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
